apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        service: service-a
        app: service-a
    spec:
      containers:
        - image: 360300935709.dkr.ecr.us-west-2.amazonaws.com/dev-service-a:de262432a890be4e70e544a8665eed498327eca0
          name: service-a
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health-status
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3    
          startupProbe:
            httpGet:
              path: /health-status
              port: 8080
            failureThreshold: 30
            periodSeconds: 10                      
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: service-a
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-a
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: capstone
  labels:
    app: service-a
spec:
  rules:
    - http:
        paths:
          - path: /bff/*
            backend:
              serviceName: service-a
              servicePort: 8080