---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::360300935709:role/template-manager-resource-podserviceaccountlinkedr-5Q8NYAS9PKG0
    eks.amazonaws.com/sts-regional-endpoints: 'true'
  name: template-manager-pods-sa
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: template-manager-rollout
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: template-manager
  strategy:
    blueGreen:
      activeService: template-manager
      previewService: template-manager-preview
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        service: template-manager
        app: template-manager
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsGroup: 1000
      serviceAccountName: template-manager-pods-sa
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: ebs-claim
      initContainers:
        - name: change-ownership-container
          image: busybox:latest
          command:
            - /bin/chmod
            - '-R'
            - '777'
            - /data
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
      containers:
        - image: 360300935709.dkr.ecr.us-west-2.amazonaws.com/dev-template-manager:a284f88a07b1caac7fa0c5eccfbd51ff777d5caa
          name: template-manager
          volumeMounts:
            - name: persistent-storage
              mountPath: /data
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          livenessProbe:
            httpGet:
              path: /health-status
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /health-status
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: template-manager
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: template-manager
---
apiVersion: v1
kind: Service
metadata:
  name: template-manager-preview
spec:
  ports:
    - port: 8080
      protocol: TCP
  type: ClusterIP
  selector:
    app: template-manager
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
